local Workspace = game:GetService("Workspace")
local Map = Workspace:WaitForChild("Map")
local Interactables = Map:WaitForChild("Interactables")
local PetSpawners = Interactables:WaitForChild("PetSpawners")
local BlueSpawner = PetSpawners:WaitForChild("BlueSpawner")
local BlueSpawnerSign = BlueSpawner:WaitForChild("BlueSpawnerSign")
local Primary = BlueSpawnerSign:WaitForChild("Primary")
local SurfaceGui = Primary:WaitForChild("SurfaceGui")
local ImageButton = SurfaceGui:WaitForChild("ImageButton")
local re = ImageButton:WaitForChild("RemoteEvent")
ImageButton.MouseButton1Click:Connect(
	function()
		re:FireServer()
	end
)
